export const ERROR = {
  INVALID_INPUT_SYNTAX: "INVALID_INPUT_SYNTAX"
};

export const MESSAGE_TYPE = {
  NEW_SOLUTION: "NEW_SOLUTION",
  CREATED_SOLUTIONS_COUNT: "CREATED_SOLUTIONS_COUNT",
  STOP_SOLUTION_CREATION: "STOP_SOLUTION_CREATION"
};
