export const ERROR = {
  INVALID_INPUT_SYNTAX: "INVALID_INPUT_SYNTAX"
};

export const INSTANCE_TYPE = {
  RQAP: "rqap",
  QAP: "qap"
};

export const MESSAGE_TYPE = {
  NEW_SOLUTION: "NEW_SOLUTION",
  CREATED_SOLUTIONS_COUNT: "CREATED_SOLUTIONS_COUNT",
  STOP_SOLUTION_CREATION: "STOP_SOLUTION_CREATION",
  AGENT_STATE: "AGENT_STATE",
  NEW_ITERATION_SOLUTION: "NEW_ITERATION_SOLUTION",
  NEW_ITERATION_BEST_SOLUTION: "NEW_ITERATION_BEST_SOLUTION"
};
