export default {
  population: [
    {
      found: 1,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 10,
          pBestPopulationWeight: 9,
          gBestPopulationWeight: 13,
          rndWeight: 1
        }
      },
      quality: 6342,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6342,
        permutation: [
          [14],
          [17],
          [2],
          [26],
          [13],
          [3],
          [16],
          [22],
          [21],
          [10],
          [7],
          [19],
          [0],
          [11],
          [6],
          [9],
          [18],
          [29],
          [23],
          [5],
          [12],
          [8],
          [28],
          [15],
          [4],
          [1],
          [20],
          [25],
          [24],
          [27]
        ],
        quality: 6342
      },
      runtime: 1967.160691998899,
      id: "sol_3_7_10_9_13_1"
    },
    {
      found: 2,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 11,
          pBestPopulationWeight: 12,
          gBestPopulationWeight: 18,
          rndWeight: 3
        }
      },
      quality: 6482,
      n: 1,
      createdSolutions: 10200,
      best: [
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6300,
          permutation: [
            [20],
            [27],
            [24],
            [7],
            [15],
            [3],
            [19],
            [12],
            [2],
            [18],
            [29],
            [13],
            [1],
            [28],
            [8],
            [6],
            [26],
            [10],
            [25],
            [5],
            [9],
            [21],
            [17],
            [22],
            [4],
            [23],
            [11],
            [0],
            [16],
            [14]
          ],
          quality: 6300
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6664,
          permutation: [
            [17],
            [29],
            [3],
            [18],
            [13],
            [2],
            [22],
            [26],
            [10],
            [9],
            [19],
            [28],
            [16],
            [21],
            [7],
            [6],
            [15],
            [8],
            [25],
            [23],
            [0],
            [24],
            [12],
            [1],
            [14],
            [5],
            [11],
            [27],
            [20],
            [4]
          ],
          quality: 6664
        }
      ],
      runtime: 1750.2786125000566,
      id: "sol_3_7_11_12_18_3"
    },
    {
      found: 8,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 10,
          pBestPopulationWeight: 18,
          gBestPopulationWeight: 18,
          rndWeight: 3
        }
      },
      quality: 6508.000000000001,
      n: 1,
      createdSolutions: 10200,
      best: [
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6336,
          permutation: [
            [27],
            [3],
            [2],
            [20],
            [1],
            [4],
            [28],
            [29],
            [15],
            [8],
            [12],
            [5],
            [18],
            [10],
            [6],
            [9],
            [24],
            [11],
            [13],
            [7],
            [21],
            [22],
            [0],
            [23],
            [19],
            [26],
            [17],
            [25],
            [16],
            [14]
          ],
          quality: 6336
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6640,
          permutation: [
            [8],
            [16],
            [7],
            [15],
            [24],
            [3],
            [9],
            [0],
            [21],
            [6],
            [18],
            [2],
            [22],
            [17],
            [26],
            [10],
            [29],
            [28],
            [25],
            [23],
            [12],
            [19],
            [20],
            [1],
            [14],
            [11],
            [5],
            [13],
            [27],
            [4]
          ],
          quality: 6640
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6486,
          permutation: [
            [16],
            [8],
            [23],
            [11],
            [27],
            [5],
            [25],
            [9],
            [0],
            [6],
            [24],
            [12],
            [14],
            [18],
            [7],
            [21],
            [17],
            [20],
            [26],
            [28],
            [29],
            [10],
            [15],
            [1],
            [19],
            [13],
            [3],
            [22],
            [2],
            [4]
          ],
          quality: 6486
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6386,
          permutation: [
            [16],
            [23],
            [0],
            [17],
            [22],
            [14],
            [11],
            [25],
            [24],
            [21],
            [7],
            [19],
            [28],
            [9],
            [8],
            [6],
            [18],
            [13],
            [12],
            [5],
            [27],
            [10],
            [29],
            [26],
            [4],
            [1],
            [20],
            [2],
            [15],
            [3]
          ],
          quality: 6386
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6556,
          permutation: [
            [25],
            [26],
            [8],
            [29],
            [13],
            [19],
            [10],
            [9],
            [18],
            [28],
            [1],
            [3],
            [6],
            [21],
            [7],
            [15],
            [2],
            [20],
            [11],
            [0],
            [17],
            [12],
            [5],
            [27],
            [23],
            [16],
            [22],
            [24],
            [4],
            [14]
          ],
          quality: 6556
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6514,
          permutation: [
            [16],
            [24],
            [7],
            [28],
            [15],
            [27],
            [14],
            [9],
            [18],
            [12],
            [8],
            [20],
            [25],
            [10],
            [6],
            [5],
            [29],
            [3],
            [23],
            [0],
            [21],
            [1],
            [2],
            [19],
            [11],
            [22],
            [17],
            [4],
            [26],
            [13]
          ],
          quality: 6514
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6614,
          permutation: [
            [1],
            [13],
            [2],
            [29],
            [10],
            [3],
            [4],
            [28],
            [21],
            [26],
            [18],
            [7],
            [20],
            [12],
            [8],
            [22],
            [6],
            [15],
            [19],
            [5],
            [9],
            [17],
            [14],
            [27],
            [25],
            [11],
            [23],
            [0],
            [16],
            [24]
          ],
          quality: 6614
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6532,
          permutation: [
            [17],
            [21],
            [22],
            [11],
            [5],
            [0],
            [13],
            [2],
            [10],
            [25],
            [24],
            [23],
            [26],
            [7],
            [6],
            [9],
            [12],
            [16],
            [19],
            [29],
            [15],
            [8],
            [27],
            [14],
            [3],
            [18],
            [20],
            [28],
            [1],
            [4]
          ],
          quality: 6532
        }
      ],
      runtime: 1801.149143499788,
      id: "sol_3_7_10_18_18_3"
    },
    {
      found: 1,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 18,
          maxGlobalBest: 10,
          pBestPopulationWeight: 12,
          gBestPopulationWeight: 16,
          rndWeight: 3
        }
      },
      quality: 6348,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6348,
        permutation: [
          [3],
          [15],
          [2],
          [28],
          [8],
          [4],
          [26],
          [29],
          [10],
          [12],
          [9],
          [1],
          [13],
          [7],
          [18],
          [22],
          [6],
          [20],
          [19],
          [24],
          [21],
          [17],
          [0],
          [25],
          [14],
          [27],
          [5],
          [11],
          [23],
          [16]
        ],
        quality: 6348
      },
      runtime: 1739.658369999379,
      id: "sol_3_18_10_12_16_3"
    },
    {
      found: 1,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 13,
          pBestPopulationWeight: 17,
          gBestPopulationWeight: 17,
          rndWeight: 3
        }
      },
      quality: 6354,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6354,
        permutation: [
          [3],
          [13],
          [28],
          [22],
          [2],
          [4],
          [29],
          [10],
          [18],
          [21],
          [17],
          [1],
          [26],
          [7],
          [6],
          [8],
          [0],
          [20],
          [15],
          [19],
          [9],
          [12],
          [11],
          [25],
          [14],
          [27],
          [24],
          [5],
          [23],
          [16]
        ],
        quality: 6354
      },
      runtime: 1781.5637170001864,
      id: "sol_3_7_13_17_17_3"
    },
    {
      found: 5,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 10,
          pBestPopulationWeight: 1,
          gBestPopulationWeight: 18,
          rndWeight: 1
        }
      },
      quality: 6536,
      n: 1,
      createdSolutions: 10200,
      best: [
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6374,
          permutation: [
            [14],
            [23],
            [25],
            [16],
            [17],
            [22],
            [24],
            [0],
            [21],
            [7],
            [18],
            [10],
            [5],
            [11],
            [9],
            [6],
            [26],
            [15],
            [4],
            [1],
            [12],
            [8],
            [2],
            [29],
            [27],
            [20],
            [19],
            [28],
            [13],
            [3]
          ],
          quality: 6374
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6692,
          permutation: [
            [14],
            [7],
            [24],
            [16],
            [0],
            [22],
            [27],
            [26],
            [10],
            [21],
            [17],
            [13],
            [15],
            [6],
            [29],
            [18],
            [2],
            [3],
            [19],
            [9],
            [12],
            [5],
            [23],
            [11],
            [20],
            [8],
            [25],
            [28],
            [1],
            [4]
          ],
          quality: 6692
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6550,
          permutation: [
            [22],
            [11],
            [23],
            [25],
            [5],
            [4],
            [8],
            [6],
            [0],
            [16],
            [12],
            [20],
            [2],
            [7],
            [21],
            [9],
            [18],
            [24],
            [17],
            [10],
            [29],
            [15],
            [28],
            [1],
            [13],
            [3],
            [26],
            [19],
            [14],
            [27]
          ],
          quality: 6550
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6592,
          permutation: [
            [3],
            [28],
            [29],
            [26],
            [13],
            [15],
            [4],
            [1],
            [12],
            [8],
            [2],
            [19],
            [25],
            [5],
            [21],
            [9],
            [18],
            [20],
            [14],
            [22],
            [10],
            [17],
            [6],
            [7],
            [16],
            [11],
            [0],
            [23],
            [24],
            [27]
          ],
          quality: 6592
        },
        {
          singleFactoryFailureScore: 0,
          failureRiskSum: 1,
          flowDistanceSum: 6472,
          permutation: [
            [3],
            [24],
            [18],
            [10],
            [22],
            [25],
            [13],
            [15],
            [29],
            [7],
            [8],
            [16],
            [28],
            [26],
            [2],
            [6],
            [17],
            [9],
            [19],
            [20],
            [12],
            [21],
            [0],
            [23],
            [27],
            [1],
            [4],
            [5],
            [11],
            [14]
          ],
          quality: 6472
        }
      ],
      runtime: 1976.1785993993283,
      id: "sol_3_7_10_1_18_1"
    },
    {
      found: 1,
      parameters: {
        agents: 6,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 10,
          pBestPopulationWeight: 18,
          gBestPopulationWeight: 18,
          rndWeight: 1
        }
      },
      quality: 6376,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6376,
        permutation: [
          [1],
          [4],
          [22],
          [17],
          [16],
          [23],
          [20],
          [2],
          [18],
          [21],
          [0],
          [25],
          [28],
          [26],
          [7],
          [6],
          [9],
          [8],
          [19],
          [15],
          [29],
          [10],
          [12],
          [11],
          [13],
          [3],
          [27],
          [24],
          [5],
          [14]
        ],
        quality: 6376
      },
      runtime: 1715.7759980000556,
      id: "sol_6_7_10_18_18_1"
    },
    {
      found: 1,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 14,
          pBestPopulationWeight: 17,
          gBestPopulationWeight: 18,
          rndWeight: 3
        }
      },
      quality: 6382,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6382,
        permutation: [
          [11],
          [4],
          [24],
          [27],
          [1],
          [20],
          [25],
          [5],
          [21],
          [19],
          [28],
          [12],
          [23],
          [0],
          [6],
          [9],
          [18],
          [8],
          [16],
          [17],
          [7],
          [15],
          [29],
          [2],
          [14],
          [22],
          [10],
          [26],
          [13],
          [3]
        ],
        quality: 6382
      },
      runtime: 1799.6194319985807,
      id: "sol_3_7_14_17_18_3"
    },
    {
      found: 1,
      parameters: {
        agents: 6,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 11,
          pBestPopulationWeight: 17,
          gBestPopulationWeight: 17,
          rndWeight: 3
        }
      },
      quality: 6438,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6438,
        permutation: [
          [17],
          [22],
          [2],
          [3],
          [4],
          [1],
          [0],
          [21],
          [10],
          [29],
          [26],
          [13],
          [16],
          [6],
          [18],
          [15],
          [14],
          [28],
          [25],
          [9],
          [7],
          [8],
          [20],
          [19],
          [23],
          [11],
          [24],
          [12],
          [5],
          [27]
        ],
        quality: 6438
      },
      runtime: 1421.361372999847,
      id: "sol_6_7_11_17_17_3"
    },
    {
      found: 1,
      parameters: {
        agents: 3,
        agentOptions: {
          maxPersonalBest: 7,
          maxGlobalBest: 10,
          pBestPopulationWeight: 18,
          gBestPopulationWeight: 16,
          rndWeight: 3
        }
      },
      quality: 6462,
      n: 1,
      createdSolutions: 10200,
      best: {
        singleFactoryFailureScore: 0,
        failureRiskSum: 1,
        flowDistanceSum: 6462,
        permutation: [
          [4],
          [5],
          [11],
          [17],
          [0],
          [16],
          [1],
          [12],
          [21],
          [9],
          [23],
          [25],
          [20],
          [15],
          [8],
          [6],
          [10],
          [22],
          [2],
          [29],
          [28],
          [18],
          [7],
          [24],
          [3],
          [13],
          [19],
          [26],
          [27],
          [14]
        ],
        quality: 6462
      },
      runtime: 1769.3332090005279,
      id: "sol_3_7_10_18_16_3"
    }
  ],
  maxIterations: 1000,
  maxBestSolutions: 10,
  rndWeight: 1,
  populationWeight: 10,
  best: {
    found: 1,
    parameters: {
      agents: 3,
      agentOptions: {
        maxPersonalBest: 7,
        maxGlobalBest: 10,
        pBestPopulationWeight: 9,
        gBestPopulationWeight: 13,
        rndWeight: 1
      }
    },
    quality: 6342,
    n: 1,
    createdSolutions: 10200,
    best: {
      singleFactoryFailureScore: 0,
      failureRiskSum: 1,
      flowDistanceSum: 6342,
      permutation: [
        [14],
        [17],
        [2],
        [26],
        [13],
        [3],
        [16],
        [22],
        [21],
        [10],
        [7],
        [19],
        [0],
        [11],
        [6],
        [9],
        [18],
        [29],
        [23],
        [5],
        [12],
        [8],
        [28],
        [15],
        [4],
        [1],
        [20],
        [25],
        [24],
        [27]
      ],
      quality: 6342
    },
    runtime: 1967.160691998899,
    id: "sol_3_7_10_9_13_1"
  }
};
